const lessonTitle = "马说";

const lessonData = [
    // ===== 第1段 =====
    ["世", "shì", "In the world", "Di dunia", "世上"],
    ["有", "yǒu", "there is", "ada", "有"],
    ["伯乐", "bó lè", "Bole", "Bole", "伯乐"],
    ["，", "", "", "", ""],
    ["然后", "rán hòu", "then only", "barulah", "这样之后"],
    ["有", "yǒu", "there is", "ada", "有"],
    ["千里马", "qiān lǐ mǎ", "a thousand-li horse", "kuda berlari seribu li", "千里马"],
    ["。", "", "", "", ""],
    ["千里马", "qiān lǐ mǎ", "Thousand-li horses", "Kuda berlari seribu li", "千里马"],
    ["常有", "cháng yǒu", "are often found", "sering ada", "常有"],
    ["，", "", "", "", ""],
    ["而", "ér", "but", "tetapi", "但是"],
    ["伯乐", "bó lè", "Bole", "Bole", "伯乐"],
    ["不常有", "bù cháng yǒu", "are not often found", "jarang ada", "不常有"],
    ["。", "", "", "", ""],
    ["故", "gù", "Therefore", "Oleh itu", "因此"],
    ["虽", "suī", "although", "walaupun", "虽然"],
    ["有", "yǒu", "there are", "ada", "有"],
    ["名马", "míng mǎ", "famous horses", "kuda terkenal", "名马"],
    ["，", "", "", "", ""],
    ["只", "zhǐ", "only", "hanya", "只能"],
    ["辱于", "rǔ yú", "be humiliated by", "dihina oleh", "屈辱于"],
    ["奴隶人", "nú lì rén", "slave hands", "tangan hamba", "奴隶人"],
    ["之手", "zhī shǒu", "", "", "的手中"],
    ["，", "", "", "", ""],
    ["骈死", "pián sǐ", "die side by side", "mati bersama-sama", "成双成对地死去"],
    ["于", "yú", "in", "di", "在"],
    ["槽枥", "cáo lì", "stables", "kandang", "马槽"],
    ["之间", "zhī jiān", "between", "antara", "之间"],
    ["，", "", "", "", ""],
    ["不以", "bù yǐ", "not by", "tidak dengan", "不因为"],
    ["千里", "qiān lǐ", "a thousand li", "seribu li", "千里"],
    ["称也", "chēng yě", "be renowned", "dikenali", "著称"],
    ["。", "", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["马之千里者", "mǎ zhī qiān lǐ zhě", "A horse that can run a thousand li", "Kuda yang mampu berlari seribu li", "千里马"],
    ["，", "", "", "", ""],
    ["一食", "yī shí", "one meal", "satu hidangan", "吃一顿"],
    ["或", "huò", "sometimes", "kadang-kadang", "有时"],
    ["尽", "jìn", "finish", "menghabiskan", "吃完"],
    ["粟", "sù", "grain", "biji-bijian", "小米"],
    ["一石", "yī dàn", "one dan", "satu dan", "一石"],
    ["。", "", "", "", ""],
    ["食马者", "sì mǎ zhě", "The one who feeds the horse", "Orang yang memberi makan kuda", "喂马的人"],
    ["不知", "bù zhī", "does not know", "tidak tahu", "不知道"],
    ["其", "qí", "it", "nya", "它"],
    ["能千里", "néng qiān lǐ", "can run a thousand li", "mampu berlari seribu li", "能日行千里"],
    ["而食也", "ér sì yě", "to feed it", "untuk memberinya makan", "来喂养它"],
    ["。", "", "", "", ""],
    ["是马也", "shì mǎ yě", "This horse", "Kuda ini", "这匹马"],
    ["，", "", "", "", ""],
    ["虽", "suī", "although", "walaupun", "虽然"],
    ["有", "yǒu", "has", "mempunyai", "有"],
    ["千里之能", "qiān lǐ zhī néng", "ability to run a thousand li", "kemampuan berlari seribu li", "日行千里的才能"],
    ["，", "", "", "", ""],
    ["食不饱", "shí bù bǎo", "not fed enough", "tidak cukup makan", "吃不饱"],
    ["，", "", "", "", ""],
    ["力不足", "lì bù zú", "strength is insufficient", "kekuatan tidak cukup", "力气不足"],
    ["，", "", "", "", ""],
    ["才美", "cái měi", "talent and beauty", "bakat dan keindahan", "才华和优点"],
    ["不外见", "bù wài xiàn", "cannot be shown outwardly", "tidak dapat ditunjukkan", "不能向外表现"],
    ["，", "", "", "", ""],
    ["且", "qiě", "moreover", "lagi pula", "尚且"],
    ["欲", "yù", "wish", "ingin", "想要"],
    ["与", "yǔ", "with", "dengan", "和"],
    ["常马", "cháng mǎ", "ordinary horses", "kuda biasa", "普通马"],
    ["等", "děng", "equal", "sama", "等同"],
    ["不可得", "bù kě dé", "cannot be achieved", "tidak dapat dicapai", "都办不到"],
    ["，", "", "", "", ""],
    ["安求", "ān qiú", "how can one expect", "bagaimana boleh mengharapkan", "怎么能要求"],
    ["其", "qí", "it", "nya", "它"],
    ["能千里也", "néng qiān lǐ yě", "to run a thousand li", "berlari seribu li", "日行千里呢"],
    ["！", "", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["策之", "cè zhī", "Whip it", "Mencambuknya", "鞭策它"],
    ["不以", "bù yǐ", "not in the", "tidak dengan", "不按照"],
    ["其道", "qí dào", "right way", "cara yang betul", "正确的方法"],
    ["，", "", "", "", ""],
    ["食之", "sì zhī", "feed it", "memberinya makan", "喂养它"],
    ["不能", "bù néng", "cannot", "tidak dapat", "不能够"],
    ["尽其材", "jìn qí cái", "exhaust its talent", "menggunakan sepenuhnya bakatnya", "发挥它的才能"],
    ["，", "", "", "", ""],
    ["鸣之", "míng zhī", "hear it neigh", "mendengarnya meringkik", "听它嘶鸣"],
    ["而", "ér", "but", "tetapi", "却"],
    ["不能", "bù néng", "cannot", "tidak dapat", "不能"],
    ["通其意", "tōng qí yì", "understand its meaning", "memahami maksudnya", "懂得它的心意"],
    ["，", "", "", "", ""],
    ["执策", "zhí cè", "holding the whip", "memegang cambuk", "拿着鞭子"],
    ["而临之", "ér lín zhī", "and facing it", "dan menghadapinya", "面对着它"],
    ["曰", "yuē", "says", "berkata", "说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["天下", "tiān xià", "Under heaven", "Di dunia", "天下"],
    ["无马", "wú mǎ", "there is no horse", "tiada kuda", "没有好马"],
    ["！”", "", "", "", ""],
    ["呜呼", "wū hū", "Alas", "Aduhai", "唉"],
    ["！", "", "", "", ""],
    ["其", "qí", "Is it", "Adakah", "难道"],
    ["真", "zhēn", "really", "benar-benar", "真的"],
    ["无马邪", "wú mǎ xié", "no horse?", "tiada kuda?", "没有好马吗"],
    ["？", "", "", "", ""],
    ["其", "qí", "Is it", "Adakah", "难道"],
    ["真", "zhēn", "really", "benar-benar", "真的"],
    ["不知马也", "bù zhī mǎ yě", "does not know horses", "tidak mengenali kuda", "不认识好马"],
    ["！", "", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", "", ""],
    ["韩愈", "hán yù", "Han Yu", "Han Yu", "韩愈"],
    ["《", "", "", "", ""],
    ["马说", "mǎ shuō", "On the Horse", "Mengenai Kuda", "马说"],
    ["》", "", "", "", ""],
    ["，", "", "", "", ""],
    ["有", "yǒu", "with", "ada", "有"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai", "改动"],
    ["）", "", "", "", ""]
];
